### PR TITLE
Made the bot work with the rewrite

### PR DESCRIPTION
**Pull request by AdamAtomus**
I updated the bot to work with the rewrite and fixed a few punctuation errors.

### CODE REVIEW

**Comment by DerpDays** [comment]
To be honest, the whole bot needs a rewrite at this point since its over 2 years old and my code quality has significantly improved, do you think that I should rewrite it/is there interest in it?

**Comment by AdamAtomus** [comment]
There is a need for better opensource bots. There are little that are actually useful.

**Comment by DerpDays** [comment]
Alright ill end up rewriting it all completely soon then, since its only a small niche bot it shouldn't take long. Should i support storing suggestions in a database (optionally of course) and are there any major needs that the current bot doesn't have that the new one should?

**Comment by DerpDays** [comment]
@AdamAtomus so any suggestions on what to use to store it all? i was thinking mongodb but then that requires an extra setup step so maybe sqllite? also any new commands etc that would be useful or like admin commands to control it

**Comment by AdamAtomus** [comment]
You could do both, I personally would use MongoDB, but most people would choose SQLlite. Sorry about not replying early, I was not paying attention to my email.

**Comment by AdamAtomus** [comment]
And I personally would add a feature to where people can just !suggest in a channel and it posts it in the same channel + deletes any messages without [p]suggest

**Comment by DerpDays** [comment]
Hmmm maybe yeah, alright ima start working on it now, i guess, and ill make the db part optional to use sqlite or something else local or mongo

**Comment by AdamAtomus** [comment]
Closed due to inactivity.

**Pull request closed without merging**
